[package]
authors = ["Zondax GmbH <info@zondax.ch>"]
name = "rslib"
version = "0.1.0"
edition = "2018"
readme = "README.md"

[lib]
name = "rslib"
crate-type = ["staticlib"]

[features]
baking = []
wallet = []
dev = ["sha2", "once_cell"]
default = []

[dependencies]
bolos-sys = { path = "../bolos" }
zemu-sys = { path = "../zemu" }

nom = { version = "6.1.2", default-features = false }
arrayvec = { version = "0.5.1", default-features = false }
git-testament = { version = "0.2", default-features = false, git = "https://github.com/becominginsane/git-testament" }
cfg-if = "1.0.0"
no-std-compat = { version = "0.4" }

#dev
sha2 = { version = "0.9", default-features = false, optional = true }
once_cell = { version = "1", default-features = false, optional = true }

[target.thumbv6m-none-eabi.dev-dependencies]
panic-halt = "0.2.0"

[dev-dependencies]
no-std-compat = { version = "0.4", features = ["std"] }
serial_test = "0.5"

[profile.release]
lto = false
codegen-units = 1
debug = true
opt-level = "s"

[profile.dev]
panic = "abort"
