#ifndef DEFINES_H_
#define DEFINES_H_

#define HAVE_ECC
#define HAVE_ECC_WEIERSTRASS
#define HAVE_ECC_TWISTED_EDWARDS
#define HAVE_ECC_MONTGOMERY

#define HAVE_ECDSA
#define HAVE_EDDSA

#define HAVE_SECP_CURVES
#define HAVE_BRAINPOOL_CURVES
#define HAVE_ANSSI_CURVES
#define HAVE_STARK_CURVES
#define HAVE_BLS12_381_G1_CURVE
#define HAVE_ED_CURVES
#define HAVE_CV_CURVES

#define HAVE_HASH
#define HAVE_BLAKE2
#define HAVE_SHA256
#define HAVE_SHA512

#define HAVE_HMAC

#endif // DEFINES_H_
